# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0785fac634e6107fdecadb0335b5b3069bed1864f0bd469c0deb2e4be9c84195eda433ad0820424f130ae833e1642a7a5d875f15d3f388267ade73462abac2d

test:
  secret_key_base: 5c7a1beb1f49ee0834acdd6a32ec35bb52b6824934681a3777449b0a8670f245afd8d57f0aa0de60df42361a898c6474de12720cbbbc121b4e93edbb0b374fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
